#
# PROGRAM: Assignment 1
# AUTHOR:  Francisco Banda
#

  CXXFLAGS = -Wall -Werror -std=c++11

  z1912220_project1: z1912220_project1.o
		g++ $(CXXFLAGS) -o z1912220_project1 z1912220_project1.o

  z1912220_project1.o: z1912220_project1.cpp
		g++ $(CXXFLAGS) -c z1912220_project1.cpp

  clean: 
		rm -f *.o z1912220_project1